name: what time is it

on: [push, pull request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - run: echo
      - run: du -skh --exclude=".git"
            